version: '3.8'

services:
  kafka: # https://hub.docker.com/r/confluentinc/cp-kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zooKeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zooKeeper
    image: 'confluentinc/cp-kafka:5.5.3'
    ports:
      - '9092:9092'

  zooKeeper: # https://hub.docker.com/r/confluentinc/cp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: '2181'
    image: 'confluentinc/cp-zookeeper:5.2.2'
    ports:
      - '2181:2181'

  schemaRegistry: # https://hub.docker.com/r/confluentinc/cp-schema-registry
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zooKeeper:2181'
      SCHEMA_REGISTRY_HOST_NAME: localhost
    image: 'confluentinc/cp-schema-registry:5.5.3'
    ports:
      - '8982:8081'

  avro_tools: # https://hub.docker.com/r/coderfi/avro-tools
    image: coderfi/avro-tools:1.7.7
    ports:
     - '9999:9999'